# Generated by Django 3.1 on 2020-08-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product1_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(max_length=20)),
            ],
        ),
    ]
